"""
deploy_validator.py — Post-deploy reconciliation & validation.

Runs after containers start and init scripts complete.
Validates buckets, Iceberg tables, and catalog connectivity.
Cleans up stale config and creates missing resources.
"""

from __future__ import annotations

import asyncio
import logging
import os
import yaml

from ..models.demo import DemoDefinition
from .compose_generator.generate import MINIO_SUBNET_REGISTRATION_SKIP_ENV
from .compose_generator.helpers import resolve_trino_aistor_catalog_name
from .docker_manager import demo_includes_minio, exec_in_container

logger = logging.getLogger(__name__)

# Dataset YAML directory — components are mounted at /app/components in Docker
DATASETS_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "..", "components", "data-generator", "datasets")
if not os.path.isdir(DATASETS_DIR):
    # Fallback for Docker environment where components are at /app/components
    DATASETS_DIR = "/app/components/data-generator/datasets"


def _load_scenario(scenario_id: str) -> dict | None:
    """Load a scenario YAML from the datasets directory."""
    path = os.path.join(DATASETS_DIR, f"{scenario_id}.yaml")
    if not os.path.isfile(path):
        return None
    with open(path, "r") as f:
        return yaml.safe_load(f)


def _clean_trino_output(text: str) -> str:
    """Remove jline/log4j warnings from Trino CLI output."""
    lines = text.strip().splitlines()
    return "\n".join(
        l for l in lines
        if not l.startswith("WARNING:") and "org.jline" not in l and "Log logr" not in l
    ).strip()


async def _exec(container: str, cmd: str, progress) -> tuple[int, str, str]:
    """Run a command in a container, log output."""
    exit_code, stdout, stderr = await exec_in_container(container, cmd)
    stderr = _clean_trino_output(stderr)
    stdout = _clean_trino_output(stdout) if stdout else stdout
    if exit_code != 0 and stderr:
        print(f"[validator] {container}: {stderr[:200]}")
    return exit_code, stdout, stderr


def _log(msg: str):
    """Print and log for maximum visibility."""
    print(f"[deploy-validator] {msg}")
    logger.info(msg)


def _record(results: list, step: str, status: str, detail: str) -> dict:
    """Append a result and log it."""
    icon = {"ok": "✓", "warning": "⚠", "error": "✗", "skipped": "–"}.get(status, "?")
    _log(f"  {icon} [{step}] {detail}")
    entry = {"step": step, "status": status, "detail": detail}
    results.append(entry)
    return entry


async def validate_and_reconcile(
    demo: DemoDefinition,
    project_name: str,
    progress,
) -> list[dict]:
    """
    Post-deploy validation & reconciliation.

    Steps:
    1. Wait for MinIO clusters to be healthy
    2. Validate/create required buckets on each cluster
    3. Wait for Trino readiness
    4. Reconcile Iceberg schema and tables (drop stale, create fresh)
    5. Validate catalog connectivity

    Returns a list of validation results.
    """
    results = []

    # ── Discover components ────────────────────────────────────────
    minio_clusters = {}   # cluster_label -> {lb_container, node_containers, alias}
    trino_container = None
    iceberg_rest_container = None
    generators = []       # [{container, scenario, format, bucket, s3_endpoint, cluster_label}]
    mc_shell_container = None

    # Build cluster map from nodes
    cluster_map = {}  # cluster_id -> DemoCluster
    for cluster in getattr(demo, "clusters", []):
        cluster_map[cluster.id] = cluster

    for node in demo.nodes:
        container = f"{project_name}-{node.id}"
        if node.component == "trino":
            trino_container = container
        elif node.component == "iceberg-rest":
            iceberg_rest_container = container

    # mc-shell is a sidecar generated by compose_generator when clusters, metabase, or any minio node exists
    has_clusters = bool(getattr(demo, "clusters", []))
    has_metabase = any(n.component == "metabase" for n in demo.nodes)
    has_minio_nodes = any(n.component == "minio" for n in demo.nodes)
    if has_clusters or has_metabase or has_minio_nodes:
        mc_shell_container = f"{project_name}-mc-shell"

    # Find data generators and their target clusters via edges
    for node in demo.nodes:
        if node.component != "data-generator":
            continue
        container = f"{project_name}-{node.id}"
        scenario = node.config.get("DG_SCENARIO", "ecommerce-orders")
        fmt = node.config.get("DG_FORMAT", "parquet")
        bucket = None
        target_cluster_label = None

        # Find the edge from this generator to a cluster
        for edge in demo.edges:
            if edge.source == node.id and edge.connection_type in ("structured-data", "file-push", "s3"):
                bucket = edge.connection_config.get("target_bucket", "") if edge.connection_config else ""
                # Find target cluster
                target_cluster_label = edge.target
                break

        generators.append({
            "container": container,
            "node_id": node.id,
            "scenario": scenario,
            "format": fmt,
            "bucket": bucket,
        })

    # ── Determine Trino catalog from edges / MinIO AIStor config ───────
    # AIStor Tables→Trino: catalog id comes only from MinIO/cluster config (not edge overrides).
    trino_catalogs: list[str] = []
    trino_node_id = next((n.id for n in demo.nodes if n.component == "trino"), None)
    if trino_node_id:
        if any(e.target == trino_node_id and e.connection_type == "aistor-tables" for e in demo.edges):
            cat = resolve_trino_aistor_catalog_name(demo, trino_node_id)
            if cat not in trino_catalogs:
                trino_catalogs.append(cat)
        for edge in demo.edges:
            if edge.target != trino_node_id or edge.connection_type == "aistor-tables":
                continue
            cat = (edge.connection_config or {}).get("catalog_name")
            if cat and cat not in trino_catalogs:
                trino_catalogs.append(cat)
    # Primary catalog: first non-iceberg if available, else iceberg
    primary_catalog = next((c for c in trino_catalogs if c != "iceberg"), None) or "iceberg"

    _log(f"Validating deployment: {len(generators)} generator(s), trino={'yes' if trino_container else 'no'}, iceberg-rest={'yes' if iceberg_rest_container else 'no'}, catalog={primary_catalog}")
    await progress("validation", "running", f"Validating deployment: {len(generators)} generator(s), trino={'yes' if trino_container else 'no'}")

    # ── Step 1: Wait for MinIO health ──────────────────────────────
    step1_minio_note = ""
    if demo_includes_minio(demo):
        step1_minio_note = (
            " Deploy injected MinIO SUBNET opt-out ("
            + ", ".join(f"{k}={v}" for k, v in sorted(MINIO_SUBNET_REGISTRATION_SKIP_ENV.items()))
            + ") — cluster is not registered with MinIO SUBNET."
        )
    _log(f"Step 1/5: Checking MinIO cluster health...{step1_minio_note}")
    await progress("validation", "running", f"Step 1/5: Checking MinIO cluster health...{step1_minio_note}")
    if mc_shell_container:
        for attempt in range(6):
            exit_code, stdout, _ = await _exec(mc_shell_container, "mc alias list --json", progress)
            if exit_code == 0:
                _record(results, "minio_health", "ok", "mc-shell aliases configured")
                break
            await asyncio.sleep(5)
        else:
            _record(results, "minio_health", "warning", "mc-shell not ready after 30s")
    else:
        _record(results, "minio_health", "skipped", "No mc-shell container")

    # ── Step 2: Validate/create buckets ────────────────────────────
    _log("Step 2/5: Validating buckets...")
    await progress("validation", "running", "Step 2/5: Validating buckets...")
    for gen in generators:
        scenario_data = _load_scenario(gen["scenario"])
        if not scenario_data:
            _record(results, "buckets", "warning", f"Scenario {gen['scenario']} YAML not found")
            continue

        # Determine required buckets
        required_buckets = set()
        if gen["bucket"]:
            required_buckets.add(gen["bucket"])
        # Add scenario-defined buckets
        for fmt_key, bkt in scenario_data.get("buckets", {}).items():
            if bkt:
                required_buckets.add(bkt)
        # Always need warehouse for Iceberg
        required_buckets.add("warehouse")
        # Remove any None values
        required_buckets.discard(None)
        required_buckets.discard("")

        # Create buckets via the generator container (it has boto3)
        for bkt in sorted(required_buckets):
            exit_code, stdout, stderr = await _exec(
                gen["container"],
                f'python3 -c "import boto3,os; '
                f'from botocore.client import Config; '
                f'c=boto3.client(\'s3\',endpoint_url=os.environ[\'S3_ENDPOINT\'],'
                f'aws_access_key_id=os.environ[\'S3_ACCESS_KEY\'],'
                f'aws_secret_access_key=os.environ[\'S3_SECRET_KEY\'],'
                f'config=Config(signature_version=\'s3v4\'),region_name=\'us-east-1\'); '
                f'c.head_bucket(Bucket=\'{bkt}\'); print(\'EXISTS: {bkt}\')" 2>&1 || '
                f'python3 -c "import boto3,os; '
                f'from botocore.client import Config; '
                f'c=boto3.client(\'s3\',endpoint_url=os.environ[\'S3_ENDPOINT\'],'
                f'aws_access_key_id=os.environ[\'S3_ACCESS_KEY\'],'
                f'aws_secret_access_key=os.environ[\'S3_SECRET_KEY\'],'
                f'config=Config(signature_version=\'s3v4\'),region_name=\'us-east-1\'); '
                f'c.create_bucket(Bucket=\'{bkt}\'); print(\'CREATED: {bkt}\')"',
                progress,
            )
            status = "ok" if exit_code == 0 else "error"
            detail = stdout.strip() if stdout else stderr.strip()[:100]
            _record(results, "buckets", status, detail)

    # ── Step 3: Wait for Trino readiness ───────────────────────────
    if trino_container:
        _log("Step 3/5: Waiting for Trino readiness...")
        await progress("validation", "running", "Step 3/5: Waiting for Trino readiness...")
        trino_ready = False
        for attempt in range(18):  # up to 90 seconds
            exit_code, stdout, _ = await _exec(
                trino_container,
                'sh -c \'curl -sf http://localhost:8080/v1/info 2>/dev/null || wget -qO- http://localhost:8080/v1/info 2>/dev/null\'',
                progress,
            )
            if exit_code == 0 and '"starting":false' in stdout.replace(" ", ""):
                trino_ready = True
                _record(results, "trino_health", "ok", f"Trino ready (attempt {attempt+1})")
                break
            elif exit_code == 0 and '"starting":true' in stdout.replace(" ", ""):
                await progress("validation", "running", f"Step 3/5: Trino starting up (attempt {attempt+1}/18)...")
            await asyncio.sleep(5)
        if not trino_ready:
            _record(results, "trino_health", "warning", "Trino not ready after 90s — skipping table reconciliation")
            await progress("validation", "warning", "Trino not ready — table setup deferred to generators")
            return results
    else:
        _record(results, "trino_health", "skipped", "No Trino in this demo")
        return results

    # ── Step 4: Reconcile Iceberg schema & tables ──────────────────
    await progress("validation", "running", "Step 4/5: Reconciling Iceberg tables...")

    # Create schema (ignore "already exists" errors — that's success)
    exit_code, stdout, stderr = await _exec(
        trino_container,
        f"trino --execute \"CREATE SCHEMA IF NOT EXISTS {primary_catalog}.demo\"",
        progress,
    )
    if exit_code == 0 or "already exists" in stderr.lower() or "already exists" in stdout.lower():
        _record(results, "iceberg_schema", "ok", f"Schema {primary_catalog}.demo ensured")
    else:
        _record(results, "iceberg_schema", "error", f"Schema creation failed: {stderr[:100]}")

    # For each generator's scenario, ensure the Iceberg table exists with correct schema
    reconciled_tables = set()
    for gen in generators:
        scenario_data = _load_scenario(gen["scenario"])
        if not scenario_data:
            continue

        iceberg_cfg = scenario_data.get("iceberg", {}) or {}
        table_name = iceberg_cfg.get("table", gen["scenario"].replace("-", "_"))
        # Use the namespace from the scenario config to match what the generator uses
        table_schema = iceberg_cfg.get("namespace", "demo")

        if table_name in reconciled_tables:
            continue
        reconciled_tables.add(table_name)

        full_table = f"{primary_catalog}.{table_schema}.{table_name}"

        # Check if table exists and is accessible
        exit_code, stdout, stderr = await _exec(
            trino_container,
            f'trino --execute "SELECT COUNT(*) FROM {full_table} LIMIT 1"',
            progress,
        )

        if exit_code == 0:
            _record(results, "iceberg_table", "ok", f"Table {full_table} accessible")
            continue

        # Table doesn't exist or is stale — clean up and recreate
        await progress("validation", "running", f"Step 4/5: Recreating {full_table}...")

        # Try to drop stale table (may fail if metadata is corrupt — that's ok)
        await _exec(trino_container, f'trino --execute "DROP TABLE IF EXISTS {full_table}"', progress)

        # If drop failed due to corrupt metadata, try purging via Iceberg REST API
        if iceberg_rest_container:
            for gen2 in generators:
                exit_code2, _, _ = await _exec(
                    gen2["container"],
                    f'python3 -c "import requests; '
                    f'r=requests.delete(\'http://{project_name}-iceberg-rest-5:8181/v1/namespaces/demo/tables/{table_name}\', '
                    f'params={{\'purgeRequested\': \'true\'}}); '
                    f'print(f\'Purge: {{r.status_code}}\')"',
                    progress,
                )
                break

        # Build column defs from scenario YAML and create the table
        schema_block = scenario_data.get("schema", {})
        columns = schema_block.get("columns", []) if isinstance(schema_block, dict) else schema_block
        if columns:
            type_map = {
                "string": "VARCHAR", "int32": "INTEGER", "int64": "BIGINT",
                "float32": "REAL", "float64": "DOUBLE", "boolean": "BOOLEAN",
                "timestamp": "TIMESTAMP", "date": "DATE",
            }
            col_defs = ", ".join(
                f"{col['name']} {type_map.get(col.get('type', 'string'), 'VARCHAR')}"
                for col in columns
            )
            create_sql = f"CREATE TABLE IF NOT EXISTS {full_table} ({col_defs}) WITH (format = 'PARQUET')"
            exit_code, stdout, stderr = await _exec(
                trino_container,
                f'trino --execute "{create_sql}"',
                progress,
            )
            if exit_code == 0 or "already exists" in (stderr or "").lower():
                _record(results, "iceberg_table", "ok", f"Table {full_table} created")
            else:
                _record(results, "iceberg_table", "error", f"Failed to create {full_table}: {stderr[:100]}")
        else:
            _record(results, "iceberg_table", "warning", f"No columns found for {table_name} — skipped")

    # ── Step 5: Validate catalog connectivity ──────────────────────
    await progress("validation", "running", "Step 5/5: Validating catalog connectivity...")

    if iceberg_rest_container:
        for gen in generators[:1]:  # use first generator
            exit_code, stdout, _ = await _exec(
                gen["container"],
                f'python3 -c "import requests; '
                f'r=requests.get(\'http://{project_name}-iceberg-rest-5:8181/v1/namespaces\'); '
                f'print(f\'Iceberg REST: {{r.status_code}} namespaces={{r.json()}}\')"',
                progress,
            )
            if exit_code == 0:
                _record(results, "catalog_connectivity", "ok", stdout.strip()[:150])
            else:
                _record(results, "catalog_connectivity", "warning", "Iceberg REST catalog not reachable")

    # Verify Trino can query the active catalogs
    check_catalogs = list(dict.fromkeys([primary_catalog] + [c for c in trino_catalogs if c != primary_catalog]))
    for catalog_name in check_catalogs:
        exit_code, stdout, stderr = await _exec(
            trino_container,
            f'trino --execute "SHOW SCHEMAS FROM {catalog_name}"',
            progress,
        )
        if exit_code == 0:
            _record(results, "catalog_connectivity", "ok", f"Trino catalog '{catalog_name}' accessible")
        else:
            _record(results, "catalog_connectivity", "warning", f"Trino catalog '{catalog_name}' not accessible: {stderr[:80]}")

    # ── Step 6: Setup all tables (iceberg + aistor + hive) ─────────
    _log("Step 6/7: Setting up tables across all catalogs...")
    await progress("validation", "running", "Step 6/7: Setting up tables...")
    try:
        import httpx
        async with httpx.AsyncClient(timeout=60) as client:
            resp = await client.post(f"http://localhost:9210/api/demos/{demo.id}/setup-tables")
            if resp.status_code == 200:
                table_results = resp.json().get("results", [])
                created = [r for r in table_results if r["status"] == "created"]
                existing = [r for r in table_results if r["status"] == "exists"]
                errors = [r for r in table_results if r["status"] == "error"]
                _record(results, "setup_tables", "ok",
                        f"{len(existing)} exist, {len(created)} created"
                        + (f", {len(errors)} errors" if errors else ""))
            else:
                _record(results, "setup_tables", "warning", f"setup-tables returned {resp.status_code}")
    except Exception as exc:
        _record(results, "setup_tables", "warning", f"Table setup skipped: {str(exc)[:100]}")

    # ── Step 7: Auto-create Metabase dashboards ────────────────────
    # Only if Metabase is in the demo
    metabase_in_demo = any(
        n.component == "metabase" for n in demo.nodes
    )
    if metabase_in_demo:
        _log("Step 7/7: Setting up Metabase dashboards...")
        await progress("validation", "running", "Step 7/7: Setting up Metabase dashboards...")
        # Wait for Metabase to be fully ready (it needs more time than health check)
        await asyncio.sleep(10)
        try:
            async with httpx.AsyncClient(timeout=120) as client:
                # Wait for Metabase health
                for attempt in range(12):
                    try:
                        metabase_container = f"{project_name}-metabase"
                        r = await client.get(f"http://{metabase_container}:3000/api/health")
                        if r.status_code == 200:
                            break
                    except Exception:
                        pass
                    await asyncio.sleep(10)

                resp = await client.post(f"http://localhost:9210/api/demos/{demo.id}/setup-metabase")
                if resp.status_code == 200:
                    mb_results = resp.json().get("results", [])
                    created = [r for r in mb_results if r.get("status") == "created"]
                    existing = [r for r in mb_results if r.get("status") == "exists"]
                    _record(results, "metabase_dashboards", "ok",
                            f"{len(existing)} exist, {len(created)} created")
                else:
                    _record(results, "metabase_dashboards", "warning",
                            f"setup-metabase returned {resp.status_code}")
        except Exception as exc:
            _record(results, "metabase_dashboards", "warning",
                    f"Metabase setup skipped: {str(exc)[:100]}")
    else:
        _record(results, "metabase_dashboards", "skipped", "No Metabase in this demo")

    return results
