{
 "title": "Apache Spark - Performance Metrics ",
 "description": "Monitors spark metrics using Prometheus in Kubernetes",
 "tags": [ "kubernetes" ],
 "time": { "from": "2018-09-25T14:51:46.062Z", "to": "2018-09-26T08:40:07.334Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Pod",
    "label": "Driver ID",
    "query": "label_values(kube_pod_info, pod)"
   },
   {
    "name": "Pod_ip",
    "query": "label_values(kube_pod_info{pod=\"$Pod\"}, node)"
   },
   {
    "name": "phase",
    "query": "query_result(kube_pod_status_phase{pod=\"$Pod\"})"
   },
   {
    "name": "executor",
    "label": "Executor ID",
    "query": "label_values(kube_pod_info{created_by_name=~\"$Pod\"},pod)"
   },
   { "name": "copy_of_phase" }
  ]
 },
 "panels": [
  { "title": "Driver Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Driver IP Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "repeat": "Pod",
   "content": "# $Pod_ip"
  },
  {
   "title": "Driver Status",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "repeat": "Pod",
   "content": "# $phase"
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Driver Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": " sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"}) /sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Executor Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": " sum (container_memory_working_set_bytes{pod_name=~\"^$executor$\"}) /sum (machine_memory_bytes{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 10 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$Pod$\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 10 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{pod_name=~\"^$executor$\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Driver CPU / Memory  usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "repeat": "Pod",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{ pod_name!=\"\", pod_name=\"$Pod\"}) by (pod_name)",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Driver CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "none", "label": "CPU Time" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"^$Pod$\"} [2m])) by (pod_name) ",
       "legendFormat": "Used CPU : {{pod_name}}"
      }
     ]
    },
    {
     "title": "Driver GC : Seconds",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{name=~\"$Pod\",gc=\"PS Scavenge\"}",
       "legendFormat": "{{ gc }}"
      },
      {
       "expr": "jvm_gc_collection_seconds_count{name=~\"$Pod\",gc=\"PS MarkSweep\"}",
       "legendFormat": "{{ gc }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Executor CPU /Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor :  Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{ pod_name!=\"\",pod_name=~\"$executor\"}) by (pod_name)",
       "legendFormat": "{{pod_name}} "
      }
     ]
    },
    {
     "title": "Executor  :  CPU usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "none", "label": "CPU Time" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod_name=~\"$executor\"} [4m])) by (pod_name) ",
       "legendFormat": "{{ pod_name }}"
      }
     ]
    },
    {
     "title": "Executor GC : Seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{kubernetes_pod_name=~\"$executor\",gc=\"PS Scavenge\"}",
       "legendFormat": "{{ kubernetes_pod_name }} {{ gc }}"
      },
      {
       "expr": "jvm_gc_collection_seconds_count{kubernetes_pod_name=~\"$executor\",gc=\"PS MarkSweep\"}",
       "legendFormat": "{{ kubernetes_pod_name }} {{ gc }}"
      }
     ]
    }
   ]
  },
  { "title": "Network IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Driver Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~'$Pod'}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}  Received"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~'$Pod'}[2m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}  Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~'$executor',kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}} Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~'$executor',pod_name!=\"pod\",kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}}  Received"
    }
   ]
  },
  { "title": "Disk IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod_name=~\"$Pod|$executor\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod_name,device)",
     "legendFormat": "{{pod_name }} {{device}} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod_name=~\"$Pod|$executor\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod_name,device)",
     "legendFormat": "{{pod_name }}{{device}} Write"
    }
   ]
  },
  { "title": "Spark External Shuffle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Spark Shuffle Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{pod_name=~'.*shuffle.*',kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}} Transmitted"
    }
   ]
  },
  {
   "title": "Spark Shuffle Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod_name=~'.*shuffle.*',pod_name!=\"pod\",kubernetes_io_hostname=~\"$Node\"}[2m])) by (pod_name,kubernetes_io_hostname)",
     "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}}  Received"
    }
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod_name=~\".*shuffle.*\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod_name,device)",
     "legendFormat": "{{pod_name }} {{device}} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod_name=~\".*shuffle.*\",device=~\"/dev/sd[a|c|e]\"}[2m])) by (pod_name,device)",
     "legendFormat": "{{pod_name }}{{device}} Write"
    }
   ]
  },
  {
   "title": "Memory Heap / Non - Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{name=~\"^$Pod$\",area=\"heap\"} ",
       "legendFormat": "{{ name }} "
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"^$executor$\",area=\"heap\"}",
       "legendFormat": " {{ kubernetes_pod_name }} "
      }
     ]
    },
    {
     "title": "Non Heap Memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{name=~\"$Pod\",area=\"nonheap\"}",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod_name=~\"$executor\",area=\"nonheap\"}",
       "legendFormat": "{{kubernetes_pod_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Threads & Memory Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_bytes_used{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name,pool)",
       "legendFormat": "{{ kubernetes_pod_name }} {{pool}}"
      },
      {
       "expr": "sum(jvm_memory_pool_bytes_used{name=~\"$Pod\"}) by (name,pool)",
       "legendFormat": "{{ name }} {{pool}}"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(jvm_threads_current{kubernetes_pod_name=~\"$executor\"}) by (kubernetes_pod_name)",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {
       "expr": "sum(jvm_threads_current{name=~\"$Pod\"}) by (name)",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Executor : Completed Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 10, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "spark_executor_executor_threadpool_completetasks{kubernetes_pod_name=~\"$executor\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {}
     ]
    },
    {
     "title": "Executor : Active Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "spark_executor_executor_threadpool_activetasks{kubernetes_pod_name=~\"$executor\"}",
       "legendFormat": "{{ kubernetes_pod_name }}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Miscellaneous Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors Spawned",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_info{created_by_name=~\"$Pod\"})",
       "legendFormat": "Executor Counts "
      }
     ]
    },
    {
     "title": "Packets Dropped : Network",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "container_network_receive_packets_dropped_total{pod_name=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod_name}} - Receive"
      },
      {
       "expr": "container_network_transmit_packets_dropped_total{pod_name=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod_name}} - Transmit"
      }
     ]
    },
    {
     "title": "Kubernetes Pod Slice",
     "type": "table",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 29 },
     "targets": [
      {
       "expr": "container_network_receive_bytes_total{pod_name=~\"$executor\"}"
      },
      {
       "expr": "container_network_receive_bytes_total{pod_name=~\"$Pod\"}"
      },
      {}
     ]
    }
   ]
  }
 ]
}