export const connectionColors: Record<string, string> = {
  s3: "#3b82f6",
  http: "#6b7280",
  metrics: "#22c55e",
  replication: "#a855f7",
  "site-replication": "#d946ef",
  "load-balance": "#f97316",
  data: "#6b7280",
  "metrics-query": "#22c55e",
  tiering: "#eab308",
  "file-push": "#06b6d4",
  "cluster-replication": "#a855f7",
  "cluster-site-replication": "#d946ef",
  "cluster-tiering": "#eab308",
  "iceberg-catalog": "#1565c0",
  "sql-query": "#7209b7",
  "s3-queue": "#00897b",
  "spark-submit": "#e65100",
  "hdfs": "#ff6b35",
  "failover": "#dc2626",
  "structured-data": "#059669",
  "aistor-tables": "#1565c0",
};

export const connectionLabels: Record<string, string> = {
  s3: "S3",
  http: "HTTP",
  metrics: "Metrics",
  replication: "Replication",
  "site-replication": "Site Replication",
  "load-balance": "Load Balance",
  data: "Data",
  "metrics-query": "PromQL",
  tiering: "Tiering",
  "file-push": "File Push",
  "cluster-replication": "Bucket Replication",
  "cluster-site-replication": "Site Replication",
  "cluster-tiering": "ILM Tiering",
  "iceberg-catalog": "Iceberg Catalog",
  "sql-query": "SQL Query",
  "s3-queue": "S3 Queue",
  "spark-submit": "Spark Submit",
  "hdfs": "HDFS",
  "failover": "Failover",
  "structured-data": "Data Push",
  "aistor-tables": "AIStor Tables",
};
