export const connectionColors: Record<string, string> = {
  s3: "#3b82f6",
  http: "#6b7280",
  metrics: "#22c55e",
  replication: "#a855f7",
  "site-replication": "#d946ef",
  "load-balance": "#f97316",
  data: "#6b7280",
  "metrics-query": "#22c55e",
  tiering: "#eab308",
  "file-push": "#06b6d4",
  "cluster-replication": "#a855f7",
  "cluster-site-replication": "#d946ef",
  "cluster-tiering": "#eab308",
  "iceberg-catalog": "#1565c0",
  "sql-query": "#7209b7",
  "s3-queue": "#00897b",
  "spark-submit": "#e65100",
  "hdfs": "#ff6b35",
  "failover": "#dc2626",
  "structured-data": "#059669",
  "aistor-tables": "#1565c0",
  "llm-api": "#a855f7",
  "vector-db": "#06b6d4",
  "mlflow-tracking": "#0ea5e9",
  "labeling-api": "#f472b6",
  "vector-db-milvus": "#14b8a6",
  "etcd": "#78716c",
  "workflow-api": "#f59e0b",
  "llm-gateway": "#8b5cf6",
  "kafka": "#e11d48",
  "kafka-connect": "#be123c",
  "schema-registry": "#f43f5e",
  "dremio-sql": "#7c3aed",
  "dremio-flight": "#6d28d9",
  "inference-api": "#76b900",
  "nginx-backend": "#f97316",
  "external-api": "#64748b",
  "dashboard-provision": "#7c3aed",
  webhook: "#EF9F27",
};

export function getConnectionColor(type: string): string {
  return connectionColors[type] ?? "#94a3b8";
}

export function getConnectionLabel(type: string): string {
  return connectionLabels[type] ?? type;
}

export const connectionLabels: Record<string, string> = {
  s3: "S3",
  http: "HTTP",
  metrics: "Metrics",
  replication: "Replication",
  "site-replication": "Site Replication",
  "load-balance": "Load Balance",
  data: "Data",
  "metrics-query": "PromQL",
  tiering: "Tiering",
  "file-push": "File Push",
  "cluster-replication": "Bucket Replication",
  "cluster-site-replication": "Site Replication",
  "cluster-tiering": "ILM Tiering",
  "iceberg-catalog": "Iceberg Catalog",
  "sql-query": "SQL Query",
  "s3-queue": "S3 Queue",
  "spark-submit": "Spark Submit",
  "hdfs": "HDFS",
  "failover": "Failover",
  "structured-data": "Data Push",
  "aistor-tables": "AIStor Tables (SigV4 Iceberg)",
  "llm-api": "LLM API",
  "vector-db": "Vector DB",
  "mlflow-tracking": "MLflow Tracking",
  "labeling-api": "Labeling API",
  "vector-db-milvus": "Milvus Vector DB",
  "etcd": "etcd",
  "workflow-api": "Workflow API",
  "llm-gateway": "LLM Gateway",
  "kafka": "Kafka",
  "kafka-connect": "Kafka Connect",
  "schema-registry": "Schema Registry",
  "dremio-sql": "SQL (Dremio)",
  "dremio-flight": "Arrow Flight",
  "inference-api": "Inference API",
  "nginx-backend": "Backend",
  "external-api": "External API",
  "dashboard-provision": "Dashboard Provisioning",
  webhook: "Webhook",
};
